spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dreamcatcher_db
    username: ${DB_USER_DC}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
